dist: bionic
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
matrix:
  exclude:
    - env: DJANGO_VERSION=1.11
      python: 3.7
    - env: DJANGO_VERSION=1.11
      python: 3.8
    - env: DJANGO_VERSION=2.0
      python: 3.7
    - env: DJANGO_VERSION=2.0
      python: 3.8
    - env: DJANGO_VERSION=2.1
      python: 3.5
    - env: DJANGO_VERSION=2.2
      python: 3.5
# command to install dependencies
install:
  - pip install django~=$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install python-coveralls coverage
# command to run tests
script:
  - coverage run --source='stringrenderer' manage.py test
after_success:
  - coveralls
