dist: bionic
language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
env:
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.0
  - DJANGO_VERSION=4.1
# command to install dependencies
install:
  - pip install django~=$DJANGO_VERSION
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install python-coveralls coverage
# command to run tests
script:
  - coverage run --source='stringrenderer' runtests.py
after_success:
  - coveralls
